### PR TITLE
Fix option to show only errors

### PR DESCRIPTION
**Pull request by grappler**

### CODE REVIEW

**Comment by dingo-d** [comment]
This did the trick? Because I tried in CLI to use that option, and couldn't get it to work properly...

**Comment by grappler** [comment]
This works for me.

**Comment by grappler** [comment]
This works for me, you could try `--warning-severity=0` otherwise

**Comment by dingo-d** [comment]
I tried with `--runtime-set show_warnings 1` and `--runtime-set show_warnings 0`, but the correct is `--runtime-set show_warnings true`? Guess that's why it didn't work...

**Comment by ernilambar** [comment]
@dingo-d Both `1` or `true` not working in your case?

**Comment by dingo-d** [comment]
@ernilambar Only `1` didn't work.

**Pull request merged**
