### PR TITLE
Cast PHP version as string

### LINKED ISSUE #204: Fatal error in fresh plugin activation
Error:

```
Fatal error: Uncaught TypeError: version_compare() expects parameter 1 to be string, int given in /Users/nilambarsharma/Sites/staging/wp-content/plugins/theme-sniffer/src/class-plugin.php:52 Stack trace: #0 /Users/nilambarsharma/Sites/staging/wp-content/plugins/theme-sniffer/src/class-plugin.php(52): version_compare(70402, '70000', '<') #1 /Users/nilambarsharma/Sites/staging/wp-content/plugins/theme-sniffer/theme-sniffer.php(41): Theme_Sniffer\Core\Plugin->activate() #2 /Users/nilambarsharma/Sites/staging/wp-includes/class-wp-hook.php(287): Theme_Sniffer\{closure}('') #3 /Users/nilambarsharma/Sites/staging/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /Users/nilambarsharma/Sites/staging/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /Users/nilambarsharma/Sites/staging/wp-admin/plugins.php(179): do_action('activate_theme-...') #6 {main} thrown in /Users/nilambarsharma/Sites/staging/wp-content/plugins/theme-sniffer/src/class-plugin.php on line 52
```
**To Reproduce**
1. Clone the repo.
2. Do `composer install` and `npm install`
3. Activate plugin

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 1.1.2
 - PHP Version: 7.4.2
 - WP Version: 5.4

### PR DESCRIPTION
**Pull request by ernilambar**
Cast PHP version as string

Fix #204

### CODE REVIEW

**Comment by dingo-d** [comment]
This is odd as it should work as-is. PHP will probably (should) cast the integer value of `PHP_VERSION_ID` to string when doing the comparison.

https://3v4l.org/5A0pr

**Comment by ernilambar** [comment]
Yes, its odd. And I have also seen this first time. 
`version_compare(70402, '70000', '<')` and this is giving fatal error.

May be @jrfnl have some idea about this issue.

**Comment by jrfnl** [comment]
This could (should) only happen if strict types is being enforced, which AFAIK, it isn't in this application.
See: https://3v4l.org/17GkX

So how are you invoking the application or is there anything in your setup which is causing strict types to be in effect ?

**Comment by ernilambar** [comment]
@jrfnl We are using `strict_types`. https://github.com/WPTT/theme-sniffer/blob/development/src/class-plugin.php#L8

**Comment by dingo-d** [comment]
Ok, this is then an overlook on my part. Totally forgot about strict types 🙈

**Comment by jrfnl** [comment]
Ah, well, that explains it :grinning:

**Pull request merged**
